name: porcupine
version: 0.0.1.0
synopsis: A tool to express portable, composable and reusable datascience task pipelines
description: See README at <https://github.com/tweag/porcupine#README.md>
maintainer: Yves Parès <yves.pares@tweag.io>
github: tweag/porcupine
category: Numerical, JSON

ghc-options: -Wall

dependencies:
  - base
  - aeson
  - aeson-pretty
  - amazonka
  - amazonka-core
  - amazonka-s3
  - amazonka-s3-streaming
  - binary
  - binary-orphans
  - bytestring
  - clock
  - conduit
  - conduit-extra
  - containers
  - contravariant
  - data-default
  - deepseq
  - directory
  - exceptions
  - filepath
  - formatting
  - hashable
  - katip >= 0.6.3
  - lens
  - monad-control
  - mtl
  - optparse-applicative
  - profunctors
  - resourcet
  - streaming
  - streaming-bytestring
  - streaming-conduit
  - template-haskell
  - temporary
  - text
  - unliftio-core
  - unordered-containers
  - url
  - vinyl
  - void
  - yaml

library:
  source-dirs: src
