_common: !include ../common-package.yaml

<<: *simwork-info
name:                pipeline-tools
dependencies:
- base >= 4.7 && < 5

<<: *ghc-options

library:
  exposed-modules:
    - Data.DocRecord
    - Data.DocRecord.OptParse
    - Data.Locations
    - Data.Locations.Loc
    - Data.Locations.LocationMonad
    - Data.Locations.LocationTree
    - Data.Locations.Mappings
    - Data.Representable
    - Data.HumanSerializable
    - Data.AlmostSerializable
    - Network.AWS.S3.TaskPipelineUtils
    - Streaming.TaskPipelineUtils
    - System.TaskPipeline.Tasks
    - System.TaskPipeline.Run
    - System.TaskPipeline.CLI
    - System.TaskPipeline.CLI.Overriding
    - System.TaskPipeline.Resource
  source-dirs: src
  dependencies:
    - aeson
    - amazonka
    - amazonka-core
    - amazonka-s3
    - amazonka-s3-streaming
    - basic-prelude
    - binary
    - binary-orphans
    - conduit
    - clock
    - bytestring
    - data-default
    - deepseq
    - directory
    - distributed-closure
    - exceptions
    - filepath
    - formatting
    - hashable
    - lens
    - monad-control
    - mtl
    - optparse-applicative
    - resourcet
    - streaming
    - streaming-bytestring
    - streaming-conduit
    - temporary
    - text
    - containers
    - unordered-containers
    - url
    - vinyl
    - yaml

tests:
  pipeline-tools-doctest:
    main:                DocTest.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pipeline-tools
    - doctest
