_common: !include ../common-package.yaml

<<: *simwork-info
name:                pipeline-tools
dependencies:
- base >= 4.7 && < 5

<<: *ghc-options

library:
  source-dirs: src
  dependencies:
    - aeson
    - amazonka
    - amazonka-core
    - amazonka-s3
    - basic-prelude
    - binary
    - binary-orphans
    - clock
    - bytestring
    - data-default
    - deepseq
    - directory
    - distributed-closure
    - exceptions
    - filepath
    - formatting
    - hashable
    - lens
    - monad-control
    - mtl
    - resourcet
    - streaming
    - streaming-bytestring
    - temporary
    - text
    - containers
    - unordered-containers
    - uploader
    - url

tests:
  pipeline-tools-doctest:
    main:                DocTest.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pipeline-tools
    - doctest
