name: porcupine-core
version: 0.0.1.0
synopsis: A tool to express portable, composable and reusable datascience task pipelines
description: See README at <https://github.com/tweag/porcupine#README.md>
maintainer: Yves Parès <yves.pares@tweag.io>
github: tweag/porcupine
category: Numerical, JSON
copyright: 2018 EURL Tweag, NovaDiscovery

ghc-options: -Wall

dependencies:
  - base
  - aeson
  - aeson-pretty
  - amazonka
  - amazonka-core
  - amazonka-s3
  - binary
  - binary-orphans
  - bytestring
  - clock
  - conduit
  - conduit-extra
  - containers
  - contravariant
  - data-default
  - deepseq
  - directory
  - docrecords
  - exceptions
  - filepath
  - formatting
  - foldl
  - funflow
  - hashable
  - katip >= 0.6.3
  - lens
  - mmorph
  - monad-control
  - mtl
  - optparse-applicative
  - path
  - profunctors
  - resourcet
  - retry
  - store
  - streaming
  - streaming-bytestring
  - streaming-conduit
  - template-haskell
  - temporary
  - text
  - transformers
  - transformers-base
  - unliftio-core
  - unordered-containers
  - url
  - void
  - vinyl
  - yaml

library:
  source-dirs: src

executables:
  example1:
    source-dirs: examples
    main: Example1.hs
    dependencies:
      - porcupine-core
