name: porcupine-core
version: 0.1.0.0
synopsis: A tool to express portable, composable and reusable data tasks and pipelines
description: See README at <https://github.com/tweag/porcupine#README.md>
maintainer: Yves Parès <yves.pares@tweag.io>
github: tweag/porcupine
category: Data, Numerical, JSON
copyright: 2018 EURL Tweag, NovaDiscovery

ghc-options: -Wall

dependencies:
  - base >= 4.10 && < 5
  - aeson
  - aeson-pretty
  - attoparsec
  - binary
  - binary-orphans
  - bytestring
  - cassava
  - clock
  - conduit
  - containers
  - contravariant
  - data-default
  - deepseq
  - directory
  - docrecords == 0.1.*
  - filepath
  - formatting
  - foldl
  - funflow >= 1.5.0
  - hashable
  - katip == 0.8.*
  - lens
  - monad-control
  - mtl
  - optparse-applicative
  - path
  - profunctors
  - reader-soup == 0.1.*
  - resourcet
  - safe-exceptions
  - store
  - streaming
  - streaming-bytestring
  - streaming-conduit
  - streaming-utils
  - template-haskell
  - temporary
  - text
  - transformers
  - transformers-base
  - unix
  - unliftio-core
  - unordered-containers
  - url
  - zlib
  - vector
  - vinyl
  - yaml

library:
  source-dirs: src

executables:
  example0:
    source-dirs: examples/example0
    main: Example0.hs
    dependencies:
      - porcupine-core
  example0.1:
    source-dirs: examples/example0.1
    main: Example0_1.hs
    dependencies:
      - porcupine-core
  example1:
    source-dirs: examples/example1
    main: Example1.hs
    dependencies:
      - porcupine-core
  example2:
    source-dirs: examples/example2
    main: Example2.hs
    dependencies:
      - porcupine-core
  example-radon:
    source-dirs: examples/example-radon
    main: ExampleRadon.hs
    dependencies:
      - porcupine-core
      - docrecords
      - aeson
      - unordered-containers
      - text
      - log-domain
      - monad-bayes
      - hvega
