name: porcupine-s3
version: 0.1.0.0
synopsis: A location accessor for porcupine to connect to AWS S3 sources/sinks
description: See README at <https://github.com/tweag/porcupine#README.md>
maintainer: Yves Parès <yves.pares@tweag.io>
github: tweag/porcupine
category: Numerical, JSON
copyright: 2018 EURL Tweag, NovaDiscovery

ghc-options: -Wall

dependencies:
  - base >= 4.10 && < 5
  - mtl
  - safe-exceptions
  - amazonka
  - amazonka-core
  - amazonka-s3
  - katip
  - lens
  - monad-control
  - resourcet
  - bytestring
  - streaming
  - streaming-bytestring
  - directory
  - reader-soup == 0.1.*
  - porcupine-core == 0.1.*
  - retry
  - text
  - filepath
  - conduit
  - conduit-extra

library:
  source-dirs: src

executables:
  exampleS3:
    source-dirs: examples
    main: ExampleS3.hs
    dependencies:
      - porcupine-core
      - porcupine-s3
      - docrecords
      - aeson
      - unordered-containers
